_target_: model.sam2.CustomSAM2AutomaticMaskGenerator
sam2_model_name: "sam2.1_hiera_b+"  # Must match exactly with the config file name (without .yaml)
points_per_side: 32
points_per_batch: 64
pred_iou_thresh: 0.8
stability_score_thresh: 0.95
box_nms_thresh: 0.7
crop_n_layers: 0
crop_nms_thresh: 0.7
min_mask_region_area: 0
output_mode: "coco_rle"
